{
 "title": "ULL Engine Overview",
 "tags": [
  "ull",
  "engine"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Orders Accepted (rate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(orders_accepted_total[5m])"
    }
   ]
  },
  {
   "title": "Orders Rejected ( rate )",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "increase(orders_rejected_total[5m])"
    }
   ]
  },
  {
   "title": "Fills (Count, 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "increase(orders_fills_total[5m])"
    }
   ]
  },
  {
   "title": "Filled Colume (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "increase(orders_filled_volume_total[5m])"
    }
   ]
  },
  {
   "title": "Open Orders",
   "type": "gauge",
   "targets": [
    { "expr": "orders_open" }
   ]
  },
  {
   "title": "Events Processed (rate/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(udp_receiver_processed_events_total[1m])"
    }
   ]
  }
 ]
}